### PR TITLE
Feature/customize font size

### LINKED ISSUE #101: Customize the font size on the reader
As a user, I want to be able to change the font size on the reader.

This has been requested several times, especially by older people or people with sight problems.

### PR DESCRIPTION
**Pull request by Dr-Wade**
depends on #102 
closes #101 

The "custom size" is based on a CSS property that is not supported by Firefox, it seems like (https://caniuse.com/css-zoom)
And the design shall be updated when we go for a full "settings" page.
However, I think it is a good temporary solution.

### CODE REVIEW

**Comment by Dr-Wade** [comment]
> * If you set the font size to e.g. 0.7, refresh the screen and click the smaller font icon, the value first gets NaN and on a second click it gets 0.9. Maybe when we retrieve the font size from the local storage we should convert it to a number?
Good find, this has been fixed.
> * Should we gray out the icon when you reach a limit? So that the user understands better that he got to a min/max value.
The button's opacity is now reduced when reaching an extremum
> * Sometimes the value of the font size gets weird values (like 0.7000000000000001), so you have to click one more time before you reach the limit (0.7 in this case). Maybe the solution is to keep float/double values with max 1 decimal.
I've added a toFixed(1), but given how Javascript handles decimal numbers (like, 0.99999999999999999 == 1) I can't guarantee we'll never face weird values again.
> * I find it a bit strange to customize the font size from the book content menu. The ideal place would be a settings page from where you can also switch between light and dark mode, since you quite rarely change these settings, .. but I guess it works for now, until we have that Settings page ready.
I totally agree, this is only a temporary solution until we get a proper settings page. Who should work on it? Do we still have a designer in charge of the project?

**Comment by cs1m0n** [comment]
When increasing the font size, some elements go off screen.

image

**Comment by andreasgan** [comment]
> * I find it a bit strange to customize the font size from the book content menu. The ideal place would be a settings page from where you can also switch between light and dark mode, since you quite rarely change these settings, .. but I guess it works for now, until we have that Settings page ready.

I would prefer to have theme and font-size on the reader as a simple icon-button with a popover, just like youversion, ibooks, etc. It makes it easier to find the look you want because you see the changes. It's also a shorter path for the user (because they will always be on the reader page when they think "oh dark mode would be nice now" or "this is actually a bit too small text").

**Comment by cs1m0n** [comment]
> I would prefer to have theme and font-size on the reader as a simple icon-button with a popover, just like youversion, ibooks, etc. It makes it easier to find the look you want because you see the changes. It's also a shorter path for the user (because they will always be on the reader page when they think "oh dark mode would be nice now" or "this is actually a bit too small text").

You make some interesting points, Andreas! I will create another post and add your ideas in there.

**Comment by cs1m0n** [comment]
> I would prefer to have theme and font-size on the reader as a simple icon-button with a popover, just like youversion, ibooks, etc. It makes it easier to find the look you want because you see the changes. It's also a shorter path for the user (because they will always be on the reader page when they think "oh dark mode would be nice now" or "this is actually a bit too small text").

Could you please add your comment to [this User Voice post](https://uservoice.bcc.no/posts/48/settings-profile-page)?

**Pull request merged**
