### PR TITLE
Text to speech 

### PR DESCRIPTION
**Pull request by bubavanhalen**
It's pretty simple an minimalistic. 

Im also not sure about the design, i tried to keep it closely to the design proposal https://www.figma.com/file/mhIxrcee0plKxybLJNnDg6/Portal-Literature?node-id=0%3A2966.

I wasn't sure about the icon's, i took those from BMM. 

I tried to keep in mind that we might add another / different "audio providers". 

Features: 
- Every article has a "Play" button to start the TTS local service
- If an BMM audio book is provided, the button just redirects to the bmm audio book (No Chapter selection or direct link to the track)
- There is a global pause button

There is no "Pause" option yet, looking forward to also include this. This is just a first version let me know if it's acceptable or if I didn't met guidlines / style guides etc.

### CODE REVIEW

**Comment by bubavanhalen** [comment]
Hi @cs1m0n.. 
Thank you for the review! I appreciate it! 

I just comment on the points you wrote from top to bottom: 
- On Figma which one of the 3 versions should I take as template? And is there a desktop version?  
- That's great, ill take a look. Thanks
- Will be added on the next update as mentioned in the comment, just didn't had time yet. 
- I guess only if it's already playing?
- What is the plan on further versions, as for now we don't know if the selected language is available as audiobook. So we could add a separate button with the bmm logo (https://bmm.brunstad.org/favicon.ico). So if the audiobook is only available in norwegian and i selected german, i could still listen to the german version. 

Let me know your thoughts.

**Comment by bubavanhalen** [comment]
> So, in this first step, we don't need to integrate anything with the BMM Api. We can simply open the album link.

I will remove the left over files from the PR

**Comment by cs1m0n** [comment]
- _On Figma which one of the 3 versions should I take as template? And is there a desktop version?_
The third version from left to right. We don't have a desktop version but I can request one if necessary, but it can simply scale responsively.

- _I guess only if it's already playing?_
Exactly, good point!

- _What is the plan on further versions, as for now we don't know if the selected language is available as audiobook._ 
A book is actually language-dependent. If you remember the `audioBookUrl`, it can have a value for German, but be null for Norwegian, as with "Hyrde og profet", for example.

- _So if the audiobook is only available in Norwegian and i selected German, i could still listen to the German version._
Yes, that's the idea 👍.

**Comment by cs1m0n** [comment]
Here's my personal feedback:

- playing article with audio on BMM should not open the audio player
- design/styles improvements 
  - smaller chapter number
  - timer not bold
  - remove hover from the play button
  - book content on the same line as the play button
  - change color of the top-border to gray (like in Figma)
  - **Desktop:** full-width audio player but limit the content of the audio player (648px) and show it on center
  - **Desktop:** no border radius
  - **Desktop:** only border-top (no left/right border)
  - **Mobile:** show listen button on the right (like on Desktop)
  - change design for the "Listen on BMM" button to something like in the attachment
  - maybe add a X button to close the audio player
  - listen icon bounces also on hover
  - listen icon smaller (link in Figma)
- fix long titles
  - limit 2 lines of title
  - chapter number and timer vertically centered
- clicking on another chapter (from the book content) plays that new chapter
- add a "Listen to audiobook" button on all book overview pages
  - books available on BMM have a green button which says "Listen on BMM"
  - other books have a "Listen to audiobook" button 
- in case this can be improved -> clicking pause takes quite noticeable time until it pauses the audio

**Comment by bubavanhalen** [comment]
> Here's my personal feedback:
> 
> * playing article with audio on BMM should not open the audio player ✅

> * design/styles improvements⚠️
>   
>   * smaller chapter number ✅
>   * timer not bold✅
>   * remove hover from the play button✅
>   * book content on the same line as the play button✅ (Not 100% sure if its correct now, double check this one!)  
>   * change color of the top-border to gray (like in Figma) ✅
>   * **Desktop:** full-width audio player but limit the content of the audio player (648px) and show it on center ✅
>   * **Desktop:** no border radius ✅
>   * **Desktop:** only border-top (no left/right border) ✅
>   * **Mobile:** show listen button on the right (like on Desktop) ✅
>   * change design for the "Listen on BMM" button to something like in the attachment ⚠️(which one?)
>   * maybe add a X button to close the audio player ⚠️(Pending)
>   * listen icon bounces also on hover ⚠️(Sure on this one?, only once maybe?) 
>   * listen icon smaller (link in Figma) ✅
> * fix long titles✅
>   
>   * limit 2 lines of title✅
>   * chapter number and timer vertically centered (Changed it to baseline on desktop => like in Figma, center on mobile ✅)
> * clicking on another chapter (from the book content) plays that new chapter ⚠️ Pending
> * add a "Listen to audiobook" button on all book overview pages ⚠️Pending
>   
>   * books available on BMM have a green button which says "Listen on BMM" ⚠️Pending
>   * other books have a "Listen to audiobook" button ⚠️Pending
> * in case this can be improved -> clicking pause takes quite noticeable time until it pauses the audio ❌Sadly not, its the native behaviour of the API. 


Thank you for the detailed comment, this makes it much easier to figure out what you expect. I still have some question, take a look above. As soon as I pushed changes ill update this comment and you can check the overall status here. 
Status: ⚠️Pending + waiting for answers

**Comment by cs1m0n** [comment]
>- book content on the same line as the play button
  **I pushed a commit**
  >- change design for the "Listen on BMM" button to something like in the attachment
  **Oops. sorry about the attachment. Here it is: (I commited positioning of the button. The styles have to be changed)**
  
  Listen on BMM
  
  >- listen icon bounces also on hover
  **Ok, we can drop this**

Other feedback:
- Desktop: the progress bar should also be full width, not limited to 648px
- Desktop: no left padding on the player-info
- Desktop: no right margin on the play/pause button

**Pull request merged**
